### PR TITLE
Stabilized header layout on resize

### PR DESCRIPTION
**Pull request by MitchBradley**
Resizing this widget to a narrow width garbles the header, with items overlaying one another.  The root cause is the use of absolute positioning for the toolbar.  Simple changes to the div layout fixed it, so the header looks reasonable and readable at any size.

Test: use the resize handle to make the widget narrow and observe the controls overlapping the "GCode" panel title.

### CODE REVIEW

**Comment by chilipeppr** [comment]
Was checking out those changes, but they seem to throw everything off? Is this what you're seeing? No toolbar. The gcode is showing below the body area.

image

**Comment by MitchBradley** [comment]
Here's what it looks like for me at different widths, initial and
narrowed:  Running Chrome browser on a PC.



Just speculating, but maybe you have some CSS override that depends on
the detailed tree structure of the button groups?  I eliminated one
level of grouping so the buttons would more down more readily as the
widget narrows.

**Comment by chilipeppr** [comment]
I think I had the widget collapsed when i merged your changes. Did you test
it out in collapsed mode? It is possible the body area is tied to the
header div in a way that your spans threw it off.

**Comment by MitchBradley** [comment]
By "collapsed mode", do you mean when it looks like this on startup?


If so, that appears to work, because here is what happens when I expand it:



My testing so far has been in Cloud 9 preview mode.  I have observed it
working inside the Cloud 9 UI, popped out into a separate browser, and
via the Test URL on the GitHub readme page.  I have not promoted it out
to the Chilipeppr level.

**Comment by chilipeppr** [comment]
For some reason none of your images are showing up in this message thread.

**Comment by MitchBradley** [comment]
I have been replying via email.  I will switch to github.

capture
capture

I just tested on Windows { Chrome, Firefox, IE }, iPhone { Chrome, Safari }, and Android 4.1.3 {Chrome}  All work - via the github Test URL.

**Comment by chilipeppr** [comment]
Your screenshots look perfect. Hmm. If you do the manual resizing with that
lower right corner resizer grip, does that throw it off? That's what I was
using to test the reflow of your new layout. I was trying it in expanded
and collapsed mode.

**Comment by chilipeppr** [comment]
Oh, one detail. I would collapse the widget, which is a sticky setting,
then fully reload the page in c9. That's when the layout was off.

**Comment by MitchBradley** [comment]
The resizer grip works perfectly.  I can supply some screenshots if you like - but in every case I have tried, the GCode list appears above the status panel that counts lines.  I works even in ridiculously narrow widths.

Can you elaborate on "collapse the widget"?  I have tried using the caret button, second from the right, to hide the GCode list, then reload.  That works for me.  I will try a few more scenarios.

**Comment by chilipeppr** [comment]
Hmm. Yes, that's the correct carat button I'm talking about too. It sounds
like it's working fine from your tests. Let me test further here. Maybe it
was on my end.

**Pull request merged**
