### PR TITLE
Added more support for streamlining tool changes.

### PR DESCRIPTION
**Pull request by lutorm**
It is now possible to define chunks of G-code that should be executed
when the machine pauses on an M6 and after it is unpaused again. This
can be used to automate moving to a tool change position.

The tool change dialog also now displays which tool is being switched
to (the Txx on the M6 line) so one doesn't have to bring up the serial
console to see this.

Finally, the "reposition" button in the tool change dialog now includes
resetting the coordinate system (g54 etc) that was in force when the M6
was hit, in case the user changes coordinate systems as part of the tool
change.

### CODE REVIEW

**Comment by chilipeppr** [comment]
Awesome. Any way to do a walkthrough video for everyone on these changes?
It would be good to post that into the Google+ page. Even I'm curious how
they work.

**Comment by lutorm** [comment]
Heh, given that I've never written a line of javascript before yesterday I have a hard time believing that it would be complicated... ;-)

Thanks for those tutorial videos, btw. Without them I wouldn't have had a chance.

Did you mean a video about the code changes or how to use them for tool changes? I added my example at https://github.com/synthetos/g2/issues/156 where somone coincidentally wondered how to do the same thing within g2.

**Comment by chilipeppr** [comment]
Yeah, I was thinking just a video to show off your changes. Any new item
like that is always worth a video under the notion if a picture is worth
1000 words, a video is worth 10,000 words.

**Comment by chilipeppr** [comment]
Changes are pushed and in production. I have not had a chance to test them though. Can you perhaps put a screenshot post into the Google+ to let folks know that way if any bugs pop up people sort of can trace it back to the G+ post?

**Comment by lutorm** [comment]
Cool. I'll make a simple video tonight to explain how to use it and post
that.

**Comment by lutorm** [comment]
Hmm. I guess the url needs changing back to the chilipeppr repo rather than my fork... You should probably regenerate the "auto generated html" and the readme from your repo, right?

**Pull request merged**
